parameters:
#    pure_machine_sdk.example.class: PureMachine\Bundle\SDKBundle\Example

services:
#    pure_machine_sdk.example:
#        class: %pure_machine_sdk.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
