services:

    pure_machine.sdk.web_service_client:
        class: PureMachine\Bundle\SDKBundle\Service\WebServiceClient
        calls:
            - [setContainer, ["@service_container"] ]

    pure_machine.sdk.http_helper:
        class: PureMachine\Bundle\SDKBundle\Service\HttpHelper
        calls:
          - [setContainer, ["@service_container"] ]

    pure_machine.sdk.string_helper:
        class: PureMachine\Bundle\SDKBundle\Service\StringHelper
